# See https://github.com/andyw8/setup-rails for more information

name: Verify
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_call:

jobs:
  verify:
    uses: setup-rails/setup-rails/.github/workflows/verify.yml@v1
    # uncomment to enable options:
    #
    # with:
    #   brakeman: true
    #   bundler-audit: true
    #   rspec: true
    #   rubocop: true
    # standard: true
